create table if not exists public.users (
    id integer generated by default as identity primary key,
    email varchar(255) unique,
    name varchar(255),
    plan_type varchar(50) not null default 'free',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.projects (
    id integer generated by default as identity primary key,
    user_id integer references public.users(id) on delete set null,
    project_name varchar(255) not null,
    category varchar(100) not null,
    budget_rmb double precision not null,
    marketplace varchar(20) not null default 'US',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.keywords (
    id integer generated by default as identity primary key,
    project_id integer not null references public.projects(id) on delete cascade,
    keyword varchar(255) not null,
    marketplace varchar(20) not null default 'US',
    category varchar(100) not null,
    monthly_search_volume integer not null default 0,
    avg_price double precision not null default 0,
    avg_rating double precision not null default 0,
    avg_reviews_top10 double precision not null default 0,
    avg_reviews_top3 double precision not null default 0,
    min_reviews_top10 integer not null default 0,
    sponsored_density double precision not null default 0,
    amazon_basics_present boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.products (
    id integer generated by default as identity primary key,
    asin varchar(20) not null unique,
    marketplace varchar(20) not null default 'US',
    title text not null,
    brand varchar(255),
    price double precision,
    rating double precision,
    review_count integer,
    monthly_sales_est integer,
    monthly_revenue_est double precision,
    bsr integer,
    is_sponsored boolean not null default false,
    seller_type varchar(100),
    image_url text,
    product_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.keyword_product_snapshots (
    id integer generated by default as identity primary key,
    keyword_id integer not null references public.keywords(id) on delete cascade,
    product_id integer not null references public.products(id) on delete cascade,
    asin varchar(20) not null,
    organic_rank integer,
    sponsored_rank integer,
    page_no integer not null default 1,
    is_sponsored boolean not null default false,
    price double precision,
    rating double precision,
    review_count integer,
    captured_at timestamptz not null default now()
);

create table if not exists public.selection_reports (
    id integer generated by default as identity primary key,
    project_id integer not null references public.projects(id) on delete cascade,
    keyword_id integer not null references public.keywords(id) on delete cascade,
    nsfs_score double precision not null,
    demand_score double precision not null,
    competition_score double precision not null,
    profit_score double precision not null,
    opportunity_score double precision not null,
    recommendation varchar(100) not null,
    risk_level varchar(50) not null,
    summary text not null,
    key_risks jsonb not null default '[]'::jsonb,
    key_opportunities jsonb not null default '[]'::jsonb,
    action_suggestions jsonb not null default '[]'::jsonb,
    products_snapshot jsonb not null default '[]'::jsonb,
    score_details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists ix_projects_user_id on public.projects(user_id);
create index if not exists ix_keywords_keyword on public.keywords(keyword);
create index if not exists ix_keywords_project_id on public.keywords(project_id);
create index if not exists ix_products_asin on public.products(asin);
create index if not exists ix_keyword_product_snapshots_keyword_id on public.keyword_product_snapshots(keyword_id);
create index if not exists ix_keyword_product_snapshots_product_id on public.keyword_product_snapshots(product_id);
create index if not exists ix_keyword_product_snapshots_asin on public.keyword_product_snapshots(asin);
create index if not exists ix_selection_reports_project_id on public.selection_reports(project_id);
create index if not exists ix_selection_reports_keyword_id on public.selection_reports(keyword_id);
create index if not exists ix_selection_reports_created_at on public.selection_reports(created_at desc);

alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.keywords enable row level security;
alter table public.products enable row level security;
alter table public.keyword_product_snapshots enable row level security;
alter table public.selection_reports enable row level security;

