create table if not exists public.scraper_runs (
    id integer generated by default as identity primary key,
    keyword varchar(255) not null,
    marketplace varchar(20) not null default 'US',
    provider varchar(50) not null,
    status varchar(50) not null,
    product_count integer not null default 0,
    error_message text,
    started_at timestamptz not null default now(),
    finished_at timestamptz
);

alter table public.selection_reports
    add column if not exists scraper_run_id integer references public.scraper_runs(id) on delete set null;

create index if not exists ix_scraper_runs_keyword on public.scraper_runs(keyword);
create index if not exists ix_scraper_runs_provider on public.scraper_runs(provider);
create index if not exists ix_scraper_runs_status on public.scraper_runs(status);
create index if not exists ix_scraper_runs_started_at on public.scraper_runs(started_at desc);
create index if not exists ix_selection_reports_scraper_run_id on public.selection_reports(scraper_run_id);

alter table public.scraper_runs enable row level security;
